server:
  port: 8063
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url:   jdbc:mysql://192.168.101.2:3306/drug?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong



mybatis:
  mapper-locations: classpath:mapper/*.xml


