server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: service-order
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html

  datasource:
    url:  jdbc:mysql://192.168.101.2:3306/drug?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
