server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: tree-web
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
