server:
    port: 8090
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8081/eureka/

spring:
    application:
        name: service-settlement

    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.101.72:3306/drug?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
        username: root
        password: 1234

mybatis:
     mapper-locations: classpath:mybatis/*.xml